const API_BASE_URL='http://localhost:5000'
const NANOSECONDS_PYTHON=1;
const MICROSECONDS_PYTHON=1000*NANOSECONDS_PYTHON;
const MILLISECONDS_PYTHON=1000*MICROSECONDS_PYTHON;


const MILLISECONDS_JS =1;

const SECONDS_JS = MILLISECONDS_JS*1000;

export{API_BASE_URL,MILLISECONDS_PYTHON, SECONDS_JS};